### ISSUE TITLE
Only running DTU test? 

### ISSUE THREAD

**Issue by jamespblloyd** [bartongroup/RATS#28]
If I personally only care about specific transcripts that change in isoform proportion, rather than whether the gene has isoforms that change, is it sensible to only run the test for DTU and not the gene-level test? (it is possible but not advised in the Vignette). Are there any obvious disadvantages I am missing other than a second check? 

Will the less statistical testing (no gene-levels testing) change the outcome of the DTU multiple testing correction? 

A more general question. In the transcript table after DTU and gene-level testing have both been done, does the columns named pval/pval_corr reflect the p-value/corrected p-value of just the DTU test, or of the gene-level test or some combination of the two tests? If they are for just the DTU tests, where is the gene level test results in the transcript table? 

Thanks,
James

**Comment by fruce-ki** [comment]
Firstly, they are both DTU tests. Just different approaches.

Secondly, you can run the Transcript only without problems. The other way around (genes only) is more problematic because the plots of the current version rely on the transcript level outcomes. In the next release this should not be an issue.

Omitting either method will not influence the results of the other. The methods are completely independent. Multiple correction is applied only within each method, not across them. The things being tested are different in each method, while also not being independent across the methods. So standard correction methods do not apply.

The p values in the transcripts table are for the transcript level tests only. The gene level p values are in the genes table. Keeping all the information in one table would make it very unfriendly.

**Comment by jamespblloyd** [comment]
Great! Thanks for clarifying this. It is good to know that there is no advantage over re-running my analysis with transcript-level test only.
